spring:
  datasource:
    url: "postgres://uptsrgpzaoxase:67e2648f00ec425f8f4b17a4104d200174108574fdaa6c686a1fa8b7dba02e14@ec2-54-155-61-133.eu-west-1.compute.amazonaws.com:5432/dbc0bjo3e92k82"
    username: "uptsrgpzaoxase"
    password: "67e2648f00ec425f8f4b17a4104d200174108574fdaa6c686a1fa8b7dba02e14"

  jpa:
     properties:
       hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

       javax:
         persistence:
           validation:
             mode: none
     hibernate:
       ddl-auto: validate
       show-sql: true